version: 2

node8: &node8
  working_directory: ~/parse-commit-message
  docker:
    - image: circleci/node:8

node10: &node10
  working_directory: ~/parse-commit-message
  docker:
    - image: circleci/node:10

restore_modules_cache: &restore_modules_cache
  restore_cache:
    keys:
    - parse-commit-message-{{ checksum "yarn.lock" }}
    # fallback to using the latest cache if no exact match is found
    - parse-commit-message-

jobinstall: &jobinstall
  steps:
    - checkout
    - *restore_modules_cache
    - run:
        name: Installing Dependencies
        command: yarn install
    - save_cache:
        key: parse-commit-message-{{ checksum "yarn.lock" }}
        paths: node_modules
    - run:
        name: Remove node_modules to cleanup workspace
        command: rm -rf node_modules

jobtest: &jobtest
  steps:
    - checkout
    - *restore_modules_cache
    - run:
        name: Running tests and checks
        command: yarn test
    - run:
        name: Sending test coverage to CodeCov
        command: bash <(curl -s https://codecov.io/bash)


jobs:
  install-on-node8:
    <<: *node8
    <<: *jobinstall

  test-on-node8:
    <<: *node8
    <<: *jobtest

  install-on-node10:
    <<: *node10
    <<: *jobinstall

  test-on-node10:
    <<: *node10
    <<: *jobtest

  release:
    <<: *node10
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Releasing and publishing
          command: yarn new-release

workflows:
  version: 2
  automated:
    jobs:
      - install-on-node8
      - test-on-node8:
          requires:
            - install-on-node8
      - install-on-node10
      - test-on-node10:
          requires:
            - install-on-node10
      - release:
          requires:
            - test-on-node8
            - test-on-node10
          filters:
            branches:
              only: master
          context: org-global
